### ISSUE TITLE
please tag package

### ISSUE THREAD

**Issue by cordoval** [coduo/phpspec-matcher-extension#2]

**Comment by norberttech** [comment]
I'm going to make it stable just after https://github.com/coduo/php-matcher/pull/27 and another php-matcher stable release

**Comment by cordoval** [comment]
please tag this current state as 0.1.0 if you may please, what if one wants to work with the current state before your PR #27 ? This makes full sense to tag then. So please tag, there is never an excuse to tag a package. Thanks!

**Comment by cordoval** [comment]
I will close in hopes you will tag 0.1.0 thanks
